#
#  Deploy Spectrum
#  $ docker-compose up -d
#

version: '3.7'
services: 
  spectrum-app:
    container_name: spectrum-app
    image: spectrum-app
    restart: always
    volumes:
    - ./spectrum:/app/spectrum
    - ./a_private.pem:/app/a_private.pem
    - ./a_public.pem:/app/a_public.pem
    - ./requirements.txt:/app/requirement.txt
    - ./logs:/app/logs
    - ./instance:/app/instance
    - ./run.py:/app/run.py

  firewall:
    container_name: firewall
    image: firewall
    ports:
    - "8080:80"
    - "8443:443"
    volumes:
    - ./ssl:/ssl
    restart: always